defaults:
  - _self_
  - env: genesis
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True

# LLM parameters
model: gemma-3-27b-it  # one of gemini/gemini models, I recommend one fo these two: [gemini-2.0-flash, gemma-3-27b-it]
temperature: 1.0
suffix: Gemma  # suffix for generated files (indicates LLM model)

# Eureka parameters
iteration: 5 # how many iterations of Eureka to run
sample: 16 # number of Eureka samples to generate per iteration
max_iterations: 501 # RL Policy training iterations (possibly it's too much, you can try lower values)
num_eval: 5 # number of evaluation episodes to run for the final reward
capture_video: False # whether to capture policy rollout videos

# Weights and Biases
use_wandb: False # whether to use wandb for logging
wandb_username: "" # wandb username if logging with wandb
wandb_project: "" # wandb project if logging with wandb